---
abstract: 'Helpers for Text::Amuse document formatting.'
author:
  - 'Marco Pessotto <melmothx@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.86, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Amuse-Preprocessor
no_index:
  directory:
    - t
    - inc
requires:
  HTML::PullParser: 0
  LWP::UserAgent: 0
  perl: 5.010001
resources:
  repository: https://gitorious.org/text-amuse-preprocessor
version: 0.09
