---
abstract: 'Helpers for Text::Amuse document formatting.'
author:
  - 'Marco Pessotto <melmothx@gmail.com>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Text-Amuse-Preprocessor
no_index:
  directory:
    - t
    - inc
requires:
  HTML::PullParser: '0'
  Text::Amuse: '0.15'
  perl: '5.010001'
resources:
  repository: https://github.com/melmothx/text-amuse-preprocessor
version: '0.20'
